# Start with pre-built Greengrass docker image
FROM amazon/aws-iot-greengrass:latest

# Install system dependencies and supporting services for accelerator
# (none so far)
# Set ENV_VAR for Greengrass version 1.10.0
# Install pre-req for docker including system path to docker-compose
RUN amazon-linux-extras install docker && \
    rm -rf /var/cache/amzn2extras

# Setup Greengrass to inside Docker Image and access dockerd
RUN chgrp ggc_group /opt && \
    chmod 777 /opt

# Add python packages from requirements.txt
ADD requirements.txt /
WORKDIR /
RUN pip3.7 install -r requirements.txt

# Replace entrypoint with one specific for the accelerator
COPY greengrass-entrypoint.sh /