FROM amazon/aws-iot-greengrass:1.10.0-amazonlinux

# Install system dependencies and supporting services for accelerator
# (none so far)
# Set ENV_VAR for Greengrass version 1.10.0
ARG GREENGRASS_RELEASE_URL=https://d1onfpft10uf5o.cloudfront.net/greengrass-core/downloads/1.10.0/greengrass-linux-x86-64-1.10.0.tar.gz
# Install pre-req for docker
RUN amazon-linux-extras install docker && \
    curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose  && \
    rm -rf /var/cache/amzn2extras

# Setup Greengrass to inside Docker Image and access dockerd
RUN export GREENGRASS_RELEASE=$(basename $GREENGRASS_RELEASE_URL) && \
    chgrp ggc_group /opt && \
    chmod 777 /opt

# Add python packages from requirements.txt
ADD requirements.txt /
WORKDIR /
RUN pip3.7 install -r requirements.txt

# Replace entrypoint with one that start supporting services
COPY greengrass-entrypoint.sh /